#!/bin/bash -e

function prompt() {
    unset PROMPT
}

exec 3<> $(realpath $1)

while IFS= read -u3 -r line
do
    echo "$line"
    unset PROMPT

    read -p "Are you sure you want to do this?[y/n]" PROMPT
    [ "$PROMPT" == "y" ] && {
        echo $line >> .shERIFF_tmp_ahhhhhhh;
    }
done

bash .shERIFF_tmp_ahhhhhhh
rm .shERIFF_tmp_ahhhhhhh
